# Use an official Node.js runtime as the base image
FROM node:16

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .
# Expose the port the app runs on (update as necessary)
EXPOSE 4000

# Command to run the application
#
CMD ["node", "index.js"]
